### ISSUE TITLE
scan_plist Invalid Token Exception

### ISSUE THREAD

**Issue by phutelmyer** [target/strelka#103]
**Describe the bug**
Upon running fileshot on OSX, receiving an error for scan_plist while scanning plist files.

**Expected behavior**
No exceptions, hopefully.

**Screenshots**
```
backend_1      | Traceback (most recent call last):
backend_1      |   File "/usr/local/lib/python3.6/dist-packages/strelka-0.0.0-py3.6.egg/strelka/strelka.py", line 148, in scan_wrapper
backend_1      |     self.scan(data, file, options, expire_at)
backend_1      |   File "/usr/local/lib/python3.6/dist-packages/strelka-0.0.0-py3.6.egg/strelka/scanners/scan_plist.py", line 13, in scan
backend_1      |     plist = plistlib.loads(data)
backend_1      |   File "/usr/lib/python3.6/plistlib.py", line 1024, in loads
backend_1      |     fp, fmt=fmt, use_builtin_types=use_builtin_types, dict_type=dict_type)
backend_1      |   File "/usr/lib/python3.6/plistlib.py", line 1015, in load
backend_1      |     return p.parse(fp)
backend_1      |   File "/usr/lib/python3.6/plistlib.py", line 325, in parse
backend_1      |     self.parser.ParseFile(fileobj)
backend_1      | xml.parsers.expat.ExpatError: not well-formed (invalid token): line 2, column 24
```

**Release**
 - Release: 0.19.07.26

**Additional context**
N/A

**Comment by phutelmyer** [comment]
May have to look into changing from the built in plistlib to biplist as plistlib cannot read binary plists (e.g., Safari):

https://stackoverflow.com/questions/22211674/plistlib-cant-read-safaris-plist-file:

**Comment by phutelmyer** [comment]
The above comment is not the actual issue during testing. One of the plist items I had was an improperly formatted XML file. Without modifying (fixing) the contents of the file, which is inadvisable, I am suggesting this ticket be closed as an issue with the host data rather than the scanner.
