### ISSUE TITLE
scan_html AttributeError 'startswith'

### ISSUE THREAD

**Issue by phutelmyer** [target/strelka#104]
**Describe the bug**
variable 'link' is not initialized in the scan_html scanner (line 37).

**Steps to reproduce**
1. Execution of default fileshot config on OSX.

**Expected behavior**
No errors, hopefully.

**Screenshots**
```
backend_1      | 2019-08-22 15:29:44 - [ERROR] root [strelka.scan_wrapper]: ScanHtml: exception while scanning uid aa331ccf-d87b-47b7-8343-8e7081da57bf (see traceback below)
backend_1      | Traceback (most recent call last):
backend_1      |   File "/usr/local/lib/python3.6/dist-packages/strelka-0.0.0-py3.6.egg/strelka/strelka.py", line 148, in scan_wrapper
backend_1      |     self.scan(data, file, options, expire_at)
backend_1      |   File "/usr/local/lib/python3.6/dist-packages/strelka-0.0.0-py3.6.egg/strelka/scanners/scan_html.py", line 37, in scan
backend_1      |     if link.startswith('data:') and ';base64,' in link:
backend_1      | AttributeError: 'NoneType' object has no attribute 'startswith'
backend_1      | 2019-08-22 15:32:17 - [ERROR] root [strelka.scan_wrapper]: ScanHtml: exception while scanning uid fa13e579-70d1-46d1-a2b4-f2127ee2196d (see traceback below)
backend_1      | Traceback (most recent call last):
backend_1      |   File "/usr/local/lib/python3.6/dist-packages/strelka-0.0.0-py3.6.egg/strelka/strelka.py", line 148, in scan_wrapper
backend_1      |     self.scan(data, file, options, expire_at)
backend_1      |   File "/usr/local/lib/python3.6/dist-packages/strelka-0.0.0-py3.6.egg/strelka/scanners/scan_html.py", line 37, in scan
backend_1      |     if link.startswith('data:') and ';base64,' in link:
backend_1      | AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Release**
 - Release: 0.19.07.26

**Additional context**
N/A

**Comment by jshlbrd** [comment]
Resolved in #106
