### ISSUE TITLE
Exception - ScanPe - PEFormatError - Invalid NT Headers signature.

### ISSUE THREAD

**Issue by phutelmyer** [target/strelka#116]
**Describe the bug**
The PE parsing library we use expects there to be a 0x4D5A file header.
If the "DOS magic header" is missing then the library fails out. - @bblenard

**Steps to reproduce**
Configured fileshot to scan 'text/plain' flavored files and very the output in the strelka log shows ScanPE on a text file. -@bblenard

**Expected behavior**
An exception will be thrown on the backend and the scanner will not complete.

**Screenshots**
```
ScanPe: exception while scanning uid fc32252a-c773-4cb3-b286-6856172b3eea (see traceback below)
backend_1      | Traceback (most recent call last):
backend_1      |   File "/usr/local/lib/python3.6/dist-packages/strelka-0.0.0-py3.6.egg/strelka/strelka.py", line 148, in scan_wrapper
backend_1      |     self.scan(data, file, options, expire_at)
backend_1      |   File "/usr/local/lib/python3.6/dist-packages/strelka-0.0.0-py3.6.egg/strelka/scanners/scan_pe.py", line 214, in scan
backend_1      |     pe = pefile.PE(data=data)
backend_1      |   File "/usr/local/lib/python3.6/dist-packages/pefile.py", line 1754, in _init_
backend_1      |     self._parse_(name, data, fast_load)
backend_1      |   File "/usr/local/lib/python3.6/dist-packages/pefile.py", line 1872, in _parse_
backend_1      |     raise PEFormatError('Invalid NT Headers signature. Probably a LE file')
backend_1      | pefile.PEFormatError: 'Invalid NT Headers signature. Probably a LE file'
```

**Release**
 - Release: 0.19.08.27

**Additional context**
This should be handled with an exception flag rather than a change to how data is scanned. No data modification should occur.

**Comment by phutelmyer** [comment]
Fixed in https://github.com/target/strelka/commit/ef0d3466422f928b296b98b0ee80a68eef785c50
