### ISSUE TITLE
[scan_docx] invalid distance too far back

### ISSUE THREAD

**Issue by phutelmyer** [target/strelka#121]
**Describe the bug**
Upon submission of a specific document (specificity undefined), a zlib error is throw.

Offending line:
https://github.com/target/strelka/blob/a7816bdd19e38a78c6a20a4e85543d6ba01fa18b/src/python/strelka/scanners/scan_docx.py#L23

`zlib.error: Error -3 while decompressing data: invalid distance too far back`

**Steps to reproduce**
1. Submit document with known issue. Known document is malicious and no reference will be provided here.

**Expected behavior**
No error on file scan

**Screenshots**
```backend_1      | Traceback (most recent call last):
backend_1      |   File "/usr/local/lib/python3.6/dist-packages/strelka-0.0.0-py3.6.egg/strelka/strelka.py", line 148, in scan_wrapper
backend_1      |     self.scan(data, file, options, expire_at)
backend_1      |   File "/usr/local/lib/python3.6/dist-packages/strelka-0.0.0-py3.6.egg/strelka/scanners/scan_docx.py", line 23, in scan
backend_1      |     docx_doc = docx.Document(docx_io)
backend_1      |   File "/usr/local/lib/python3.6/dist-packages/docx/api.py", line 25, in Document
backend_1      |     document_part = Package.open(docx).main_document_part
backend_1      |   File "/usr/local/lib/python3.6/dist-packages/docx/opc/package.py", line 128, in open
backend_1      |     pkg_reader = PackageReader.from_file(pkg_file)
backend_1      |   File "/usr/local/lib/python3.6/dist-packages/docx/opc/pkgreader.py", line 36, in from_file
backend_1      |     phys_reader, pkg_srels, content_types
backend_1      |   File "/usr/local/lib/python3.6/dist-packages/docx/opc/pkgreader.py", line 69, in _load_serialized_parts
backend_1      |     for partname, blob, reltype, srels in part_walker:
backend_1      |   File "/usr/local/lib/python3.6/dist-packages/docx/opc/pkgreader.py", line 110, in _walk_phys_parts
backend_1      |     for partname, blob, reltype, srels in next_walker:
backend_1      |   File "/usr/local/lib/python3.6/dist-packages/docx/opc/pkgreader.py", line 105, in _walk_phys_parts
backend_1      |     blob = phys_reader.blob_for(partname)
backend_1      |   File "/usr/local/lib/python3.6/dist-packages/docx/opc/phys_pkg.py", line 108, in blob_for
backend_1      |     return self._zipf.read(pack_uri.membername)
backend_1      |   File "/usr/lib/python3.6/zipfile.py", line 1338, in read
backend_1      |     return fp.read()
backend_1      |   File "/usr/lib/python3.6/zipfile.py", line 858, in read
backend_1      |     buf += self._read1(self.MAX_N)
backend_1      |   File "/usr/lib/python3.6/zipfile.py", line 948, in _read1
backend_1      |     data = self._decompressor.decompress(data, n)
backend_1      | zlib.error: Error -3 while decompressing data: invalid distance too far back
```

**Release**
 - Release: 0.19.08.27

**Additional context**
N/A

**Comment by phutelmyer** [comment]
This can be closed per changes noted in https://github.com/target/strelka/commit/e247f7454c5d771116dae6bab9af6db061a3d25d
