### ISSUE TITLE
docker-compose fails to build due to dependency error

### ISSUE THREAD

**Issue by phutelmyer** [target/strelka#147]
**Describe the bug**
Upon running `docker-compose build` for Strelka on `2021/13/1`, two errors are observed related to the `mmbot` package relating to dependencies: `scikit-learn`, `Cython`, and `numpy`. Strelka fails to complete the build process.

**Steps to reproduce**
1. Run `docker-compose -f ./build/docker-compose.yml` from the root directory.

**Expected behavior**
No errors, completed Strelka build.

**Screenshots**
```
  Traceback (most recent call last):
    File "/tmp/pip-build-f8e4hqbk/scikit-learn/setup.py", line 201, in check_package_status
      module = importlib.import_module(package)
    File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 994, in _gcd_import
    File "<frozen importlib._bootstrap>", line 971, in _find_and_load
    File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  ModuleNotFoundError: No module named 'numpy'
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-f8e4hqbk/scikit-learn/setup.py", line 306, in <module>
      setup_package()
    File "/tmp/pip-build-f8e4hqbk/scikit-learn/setup.py", line 292, in setup_package
      check_package_status('numpy', min_deps.NUMPY_MIN_VERSION)
    File "/tmp/pip-build-f8e4hqbk/scikit-learn/setup.py", line 227, in check_package_status
      .format(package, req_str, instructions))
  ImportError: numpy is not installed.
  scikit-learn requires numpy >= 1.13.3.
  Installation instructions are available on the scikit-learn website: http://scikit-learn.org/stable/install.html
  
  
  ----------------------------------------
  Failed building wheel for scikit-learn
  Running setup.py clean for scikit-learn
  Running setup.py bdist_wheel for colorclass: started
  Running setup.py bdist_wheel for colorclass: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/d1/86/9d/16127127306a92d7fd30267890a5634026c045391979c4c317
  Running setup.py bdist_wheel for msoffcrypto-tool: started
  Running setup.py bdist_wheel for msoffcrypto-tool: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/f4/a6/40/413c706c56b1aee940dd6873b425dd0ab4d67bd4c0d11cf6a4
  Running setup.py bdist_wheel for olefile: started
  Running setup.py bdist_wheel for olefile: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/4b/f4/11/bc4166107c27f07fd7bba707ffcb439619197638a1ac986df3
Successfully built oletools colorclass msoffcrypto-tool olefile
Failed to build scikit-learn
Installing collected packages: cython, six, grpcio, protobuf, grpcio-tools, numpy, joblib, colorclass, easygui, pycparser, cffi, cryptography, olefile, msoffcrypto-tool, pcodedmp, pyparsing, oletools, pytz, python-dateutil, pandas, scipy, threadpoolctl, scikit-learn, mmbot
  Running setup.py install for scikit-learn: started
    Running setup.py install for scikit-learn: finished with status 'error'
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-f8e4hqbk/scikit-learn/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-8zax0jyp-record/install-record.txt --single-version-externally-managed --compile:
    Partial import of sklearn during the build process.
    C compiler: x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC
    
    compile options: '-c'
    x86_64-linux-gnu-gcc: test_program.c
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/numpy/distutils/unixccompiler.py", line 51, in UnixCCompiler__compile
        extra_postargs, display = display)
      File "/usr/local/lib/python3.6/dist-packages/numpy/distutils/ccompiler.py", line 90, in <lambda>
        m = lambda self, *args, **kw: func(self, *args, **kw)
      File "/usr/local/lib/python3.6/dist-packages/numpy/distutils/ccompiler.py", line 174, in CCompiler_spawn
        (cmd, s, msg))
    distutils.errors.DistutilsExecError: Command "x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -c test_program.c -o objects/test_program.o" failed with exit status 127
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-f8e4hqbk/scikit-learn/setup.py", line 306, in <module>
        setup_package()
      File "/tmp/pip-build-f8e4hqbk/scikit-learn/setup.py", line 302, in setup_package
        setup(**metadata)
      File "/usr/local/lib/python3.6/dist-packages/numpy/distutils/core.py", line 135, in setup
        config = configuration()
      File "/tmp/pip-build-f8e4hqbk/scikit-learn/setup.py", line 188, in configuration
        config.add_subpackage('sklearn')
      File "/usr/local/lib/python3.6/dist-packages/numpy/distutils/misc_util.py", line 1020, in add_subpackage
        caller_level = 2)
      File "/usr/local/lib/python3.6/dist-packages/numpy/distutils/misc_util.py", line 989, in get_subpackage
        caller_level = caller_level + 1)
      File "/usr/local/lib/python3.6/dist-packages/numpy/distutils/misc_util.py", line 926, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "sklearn/setup.py", line 83, in configuration
        cythonize_extensions(top_path, config)
      File "/tmp/pip-build-f8e4hqbk/scikit-learn/sklearn/_build_utils/__init__.py", line 45, in cythonize_extensions
        basic_check_build()
      File "/tmp/pip-build-f8e4hqbk/scikit-learn/sklearn/_build_utils/pre_build_helpers.py", line 106, in basic_check_build
        compile_test_program(code)
      File "/tmp/pip-build-f8e4hqbk/scikit-learn/sklearn/_build_utils/pre_build_helpers.py", line 67, in compile_test_program
        extra_postargs=extra_postargs)
      File "/usr/local/lib/python3.6/dist-packages/numpy/distutils/ccompiler.py", line 90, in <lambda>
        m = lambda self, *args, **kw: func(self, *args, **kw)
      File "/usr/local/lib/python3.6/dist-packages/numpy/distutils/ccompiler.py", line 361, in CCompiler_compile
        single_compile(o)
      File "/usr/local/lib/python3.6/dist-packages/numpy/distutils/ccompiler.py", line 321, in single_compile
        self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
      File "/usr/local/lib/python3.6/dist-packages/numpy/distutils/ccompiler.py", line 90, in <lambda>
        m = lambda self, *args, **kw: func(self, *args, **kw)
      File "/usr/local/lib/python3.6/dist-packages/numpy/distutils/unixccompiler.py", line 54, in UnixCCompiler__compile
        raise CompileError(msg)
    distutils.errors.CompileError: Command "x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -c test_program.c -o objects/test_program.o" failed with exit status 127
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-f8e4hqbk/scikit-learn/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-8zax0jyp-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-f8e4hqbk/scikit-learn/
```

**Release**
 - 0.20.11.20

**Additional context**
N/A

**Comment by phutelmyer** [comment]
This was the result of a dependency issue between the version of Ubuntu used and a few dependencies. This was fixed in https://github.com/target/strelka/pull/148
