### ISSUE TITLE
Docker-compose 1.29.2 error

### ISSUE THREAD

**Issue by delbs27** [target/strelka#179]
**Describe the bug**
Using the latest docker-compose 1.29.2 on a fresh Ubuntu or Fedora latest install results in errors when building Strelka Server

**Steps to reproduce**
1. Run Install docker-compose on either linux distribution following these steps https://docs.docker.com/compose/install/   and the docker packages for the platform selected
2. installing the server of strelka following these steps https://target.github.io/strelka/#/?id=server-install
3. Then running docker-compose produces the below errors
    docker-compose -f build/docker-compose.yaml up
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1277, in request
  File "http/client.py", line 1323, in _send_request
  File "http/client.py", line 1272, in endheaders
  File "http/client.py", line 1032, in _send_output
  File "http/client.py", line 972, in send
  File "docker/transport/unixconn.py", line 43, in connect
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 449, in send
  File "urllib3/connectionpool.py", line 727, in urlopen
  File "urllib3/util/retry.py", line 410, in increment
  File "urllib3/packages/six.py", line 734, in reraise
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1277, in request
  File "http/client.py", line 1323, in _send_request
  File "http/client.py", line 1272, in endheaders
  File "http/client.py", line 1032, in _send_output
  File "http/client.py", line 972, in send
  File "docker/transport/unixconn.py", line 43, in connect
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker/api/client.py", line 214, in _retrieve_server_version
  File "docker/api/daemon.py", line 181, in version
  File "docker/utils/decorators.py", line 46, in inner
  File "docker/api/client.py", line 237, in _get
  File "requests/sessions.py", line 543, in get
  File "requests/sessions.py", line 530, in request
  File "requests/sessions.py", line 643, in send
  File "requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 200, in perform_command
  File "compose/cli/command.py", line 70, in project_from_options
  File "compose/cli/command.py", line 153, in get_project
  File "compose/cli/docker_client.py", line 43, in get_client
  File "compose/cli/docker_client.py", line 170, in docker_client
  File "docker/api/client.py", line 197, in __init__
  File "docker/api/client.py", line 222, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
[3647] Failed to execute script docker-compose

**Expected behavior**
I expect as per previous Strelka builds that it retrieves latest docker templates and associated packages and builds the server components of Strelka

**Screenshots**
CLI output above is the exact error 

**Release**
 - 1.29.2

**Additional context**
The way i worked around the problem for now is by removing this version of docker-compose and installing 1.28.6 following the documentation above and the server stack built successfully.

**Comment by delbs27** [comment]
Hey, yeah same here, could have just been docker not starting up by default after install in one of the environments, anyway i updated to 1.29.2 also and seems to work, apologies if i wasted your time. 
Thanks
