### ISSUE TITLE
Broken PNG File Causes Unrecoverable Exception(s)

### ISSUE THREAD

**Issue by ryanohoro** [target/strelka#263]
**Describe the bug**

A PNG file missing an IEND chunk causes ScanNf and/or ScanLsb to throw an exception which causes the request to Strelka to time out.

**Steps to reproduce**

```bash
./strelka-oneshot -f ../../../python/strelka/tests/fixtures/test_broken_iend.png

2022/12/27 00:24:22 rpc err:
                         code: DeadlineExceeded: 
                         message: context deadline exceeded
```

```bash
docker-compose -f build/docker-compose.yaml logs backend
Attaching to strelka_backend_1


backend_1      | libpng error: PNG input buffer is incomplete
backend_1      | 2022-12-27 06:23:22 - [ERROR] root [strelka-backend.work]: unknown exception (see traceback below)
backend_1      | Traceback (most recent call last):
backend_1      |   File "/usr/local/lib/python3.10/dist-packages/strelka-0.0.0-py3.10.egg/EGG-INFO/scripts/strelka-backend", line 88, in work
backend_1      |     self.distribute(root_id, file, expire_at)
backend_1      |   File "/usr/local/lib/python3.10/dist-packages/strelka-0.0.0-py3.10.egg/EGG-INFO/scripts/strelka-backend", line 196, in distribute
backend_1      |     (f, s) = plugin.scan_wrapper(
backend_1      |   File "/usr/local/lib/python3.10/dist-packages/strelka-0.0.0-py3.10.egg/strelka/strelka.py", line 172, in scan_wrapper
backend_1      |     self.scan(data, file, options, expire_at)
backend_1      |   File "/usr/local/lib/python3.10/dist-packages/strelka-0.0.0-py3.10.egg/strelka/scanners/scan_lsb.py", line 14, in scan
backend_1      |     bits = self._get_bits(image)
backend_1      |   File "/usr/local/lib/python3.10/dist-packages/strelka-0.0.0-py3.10.egg/strelka/scanners/scan_lsb.py", line 30, in _get_bits
backend_1      |     h, w, t = img.shape
backend_1      | AttributeError: 'NoneType' object has no attribute 'shape'

*** with ScanLsb disabled ***

backend_1      | 2022-12-27 06:32:37 - [ERROR] root [strelka-backend.work]: unknown exception (see traceback below)
backend_1      | Traceback (most recent call last):
backend_1      |   File "/usr/local/lib/python3.10/dist-packages/strelka-0.0.0-py3.10.egg/EGG-INFO/scripts/strelka-backend", line 88, in work
backend_1      |     self.distribute(root_id, file, expire_at)
backend_1      |   File "/usr/local/lib/python3.10/dist-packages/strelka-0.0.0-py3.10.egg/EGG-INFO/scripts/strelka-backend", line 196, in distribute
backend_1      |     (f, s) = plugin.scan_wrapper(
backend_1      |   File "/usr/local/lib/python3.10/dist-packages/strelka-0.0.0-py3.10.egg/strelka/strelka.py", line 172, in scan_wrapper
backend_1      |     self.scan(data, file, options, expire_at)
backend_1      |   File "/usr/local/lib/python3.10/dist-packages/strelka-0.0.0-py3.10.egg/strelka/scanners/scan_nf.py", line 23, in scan
backend_1      |     image = cv.cvtColor(np_image, cv.COLOR_BGR2HSV)
backend_1      | cv2.error: OpenCV(4.6.0) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'


```

**Expected behavior**

The request to Strelka should return with the appropriate error flags set.

**Screenshots**

**Release**
 - Release: 0.22.12.08

**Additional context**

This is a good opportunity to improve how Strelka deals with unhandled exceptions from scanners, and offer new debugging methods to developers.

**Comment by phutelmyer** [comment]
For anyone interested in troubleshooting, the file referenced that @ryanohoro noted in the above issue can be found: https://github.com/target/strelka/blob/master/src/python/strelka/tests/fixtures/test_broken_iend.png
